import { Course } from './store/features/courseSlice';

export const MOCK_COURSES: Course[] = [
  {
    id: '1',
    title: 'Advanced React Patterns & Performance',
    description: 'Master high-performance React applications using advanced patterns like Compound Components, Render Props, and custom hooks.',
    instructor: {
      name: 'Sarah Drasner',
      avatar: 'https://i.pravatar.cc/150?u=sarah',
    },
    price: 89,
    image: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?q=80&w=2070&auto=format&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?q=80&w=2070&auto=format&fit=crop',
    category: 'Web Development',
    rating: 4.9,
    studentsCount: 1240,
    level: 'Advanced',
    duration: '12h 30m',
    lessonsCount: 45,
  },
  {
    id: '2',
    title: 'Full-Stack Next.js 15 Masterclass',
    description: 'Build production-ready applications with Next.js 15, App Router, Server Actions, and PostgreSQL.',
    instructor: {
      name: 'Guillermo Rauch',
      avatar: 'https://i.pravatar.cc/150?u=guillermo',
    },
    price: 129,
    image: 'https://images.unsplash.com/photo-1622737133809-d95047b9e673?q=80&w=2070&auto=format&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1622737133809-d95047b9e673?q=80&w=2070&auto=format&fit=crop',
    category: 'Web Development',
    rating: 4.8,
    studentsCount: 3500,
    level: 'Intermediate',
    duration: '18h 45m',
    lessonsCount: 62,
  },
  {
    id: '3',
    title: 'UI/UX Design for Engineers',
    description: 'Learn the principles of design, typography, and color theory specifically tailored for software engineers.',
    instructor: {
      name: 'Gary Simon',
      avatar: 'https://i.pravatar.cc/150?u=gary',
    },
    price: 59,
    image: 'https://images.unsplash.com/photo-1558655146-d09347e92766?q=80&w=2070&auto=format&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1558655146-d09347e92766?q=80&w=2070&auto=format&fit=crop',
    category: 'Design',
    rating: 4.7,
    studentsCount: 890,
    level: 'Beginner',
    duration: '8h 15m',
    lessonsCount: 28,
  },
  {
    id: '4',
    title: 'Machine Learning with Python',
    description: 'A comprehensive guide to machine learning using Scikit-Learn, TensorFlow, and real-world datasets.',
    instructor: {
      name: 'Andrew Ng',
      avatar: 'https://i.pravatar.cc/150?u=andrew',
    },
    price: 149,
    image: 'https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?q=80&w=2070&auto=format&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?q=80&w=2070&auto=format&fit=crop',
    category: 'Data Science',
    rating: 4.9,
    studentsCount: 5200,
    level: 'Advanced',
    duration: '24h 0m',
    lessonsCount: 85,
  },
  {
    id: '5',
    title: 'Mastering TypeScript 5.0',
    description: 'Go from zero to hero with TypeScript. Learn generics, utility types, and advanced type manipulation.',
    instructor: {
      name: 'Josh Goldberg',
      avatar: 'https://i.pravatar.cc/150?u=josh',
    },
    price: 79,
    image: 'https://images.unsplash.com/photo-1516116216624-53e697fedbea?q=80&w=2128&auto=format&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1516116216624-53e697fedbea?q=80&w=2128&auto=format&fit=crop',
    category: 'Web Development',
    rating: 4.8,
    studentsCount: 2100,
    level: 'Intermediate',
    duration: '10h 20m',
    lessonsCount: 38,
  },
  {
    id: '6',
    title: 'Cloud Architecture on AWS',
    description: 'Design scalable and resilient cloud architectures using AWS services like Lambda, S3, and RDS.',
    instructor: {
      name: 'Kelsey Hightower',
      avatar: 'https://i.pravatar.cc/150?u=kelsey',
    },
    price: 199,
    image: 'https://picsum.photos/seed/cloud/800/450',
    thumbnail: 'https://picsum.photos/seed/cloud/800/450',
    category: 'Cloud Computing',
    rating: 4.6,
    studentsCount: 1500,
    level: 'Advanced',
    duration: '15h 30m',
    lessonsCount: 50,
  },
  {
    id: '7',
    title: 'C Programming: The Absolute Beginner Guide',
    description: 'Master the foundations of computer science with C. Learn memory management, pointers, and data structures.',
    instructor: {
      name: 'Dennis Ritchie',
      avatar: 'https://i.pravatar.cc/150?u=dennis',
    },
    price: 49,
    image: 'https://picsum.photos/seed/c-prog/800/450',
    thumbnail: 'https://picsum.photos/seed/c-prog/800/450',
    category: 'Programming',
    rating: 4.8,
    studentsCount: 8500,
    level: 'Beginner',
    duration: '15h 0m',
    lessonsCount: 55,
  },
  {
    id: '8',
    title: 'C++ for Game Development',
    description: 'Learn C++ from scratch with a focus on game development principles, OOP, and performance optimization.',
    instructor: {
      name: 'Bjarne Stroustrup',
      avatar: 'https://i.pravatar.cc/150?u=bjarne',
    },
    price: 99,
    image: 'https://picsum.photos/seed/cpp/800/450',
    thumbnail: 'https://picsum.photos/seed/cpp/800/450',
    category: 'Programming',
    rating: 4.9,
    studentsCount: 4200,
    level: 'Intermediate',
    duration: '22h 30m',
    lessonsCount: 78,
  },
  {
    id: '9',
    title: 'Java Enterprise Edition Masterclass',
    description: 'Build scalable enterprise applications with Java, Spring Boot, and Microservices architecture.',
    instructor: {
      name: 'James Gosling',
      avatar: 'https://i.pravatar.cc/150?u=james',
    },
    price: 119,
    image: 'https://picsum.photos/seed/java/800/450',
    thumbnail: 'https://picsum.photos/seed/java/800/450',
    category: 'Programming',
    rating: 4.7,
    studentsCount: 6100,
    level: 'Advanced',
    duration: '30h 15m',
    lessonsCount: 92,
  },
  {
    id: '10',
    title: 'Python for Data Science & AI',
    description: 'The most comprehensive Python course. From basic syntax to advanced AI libraries like PyTorch.',
    instructor: {
      name: 'Guido van Rossum',
      avatar: 'https://i.pravatar.cc/150?u=guido',
    },
    price: 79,
    image: 'https://picsum.photos/seed/python/800/450',
    thumbnail: 'https://picsum.photos/seed/python/800/450',
    category: 'Programming',
    rating: 4.9,
    studentsCount: 12000,
    level: 'Beginner',
    duration: '20h 45m',
    lessonsCount: 110,
  },
];

export const CATEGORIES = [
  { name: 'Programming', icon: 'Terminal' },
  { name: 'Web Development', icon: 'Code' },
  { name: 'Mobile Development', icon: 'Smartphone' },
  { name: 'Data Science', icon: 'Database' },
  { name: 'Design', icon: 'Palette' },
  { name: 'Cloud Computing', icon: 'Cloud' },
  { name: 'Cybersecurity', icon: 'Shield' },
];

export const TESTIMONIALS = [
  {
    id: '1',
    name: 'Alex Rivera',
    role: 'Senior Engineer at Vercel',
    content: 'Nexus Academy changed my career. The depth of the courses is unmatched in the industry.',
    avatar: 'https://picsum.photos/seed/alex/100/100',
  },
  {
    id: '2',
    name: 'Mila Kunis',
    role: 'Frontend Developer at Stripe',
    content: 'The UI/UX course for engineers was exactly what I needed to bridge the gap between code and design.',
    avatar: 'https://picsum.photos/seed/mila/100/100',
  },
  {
    id: '3',
    name: 'David Chen',
    role: 'Full-Stack Developer',
    content: 'I went from junior to senior in less than a year thanks to the mentorship and projects here.',
    avatar: 'https://picsum.photos/seed/david/100/100',
  },
];
